### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by mikaelkundert** [DCNordics/DCNordics.github.io#1]
We need initial branding for the event. Pull requests for the website are welcome!

Requirements:
- All content must be licensed under GPL v3

Guidelines:
- Initial site done in static HTML proposed as pull request to this repository
- Must be nordicness!
- Deadline by 21.10.

Anyone can give feedback on pull requests. If many pull requests are introduced, voting will take place during friday 21.10. - therefore you may either compete on branding or just work on one branch :)

Winner will be rewarded somehow.

**Remember, this is first iteration, nothing needs to be just perfect at first!**

**Comment by mikaelkundert** [comment]
And suggested copy texts are:

- DrupalCamp Nordics 2017
- Stay tuned and follow us on Twitter or subscribe for a newsletter!

**Comment by oetseli** [comment]
I created a styletile and initial temporary index.html for the "Follow on Twitter and subscribe to our mailing list" phase. It's on the branding/suggestion-1 branch: https://github.com/DCNordics/DCNordics.github.io/tree/branding/suggestion-1

**Comment by oetseli** [comment]
By the way, the iconset on my styletile seems to be an unlicensed freebie. I have to contact the creator and ask if she could license it as CC-BY which should be compatible with GPLv3. Otherwise we can't take the risk of using that set and we'll just have to pick another one... or make our own, because I'm not sure we need that many icons and they are really simple on purpose.

**Comment by mikaelkundert** [comment]
First iteration has been published with little adjustments.

Here are some aggregated comments:
* Lets try to find some other fonts
* We could use some type of scandinavic design (for instance something like https://designschool.canva.com/wp-content/uploads/sites/2/2016/03/Scandinavian-Graphic-Design_FACEBOOK.png )
* Cartoonish footer doesn't work

**Comment by idevit** [comment]
twitter cover proposal:
https://github.com/DCNordics/DCNordics.github.io/tree/master/docs/twitter

Background image credits wikipedia:
https://commons.wikimedia.org/wiki/File:Catedral_Luterana_de_Helsinki,_Finlandia,_2012-08-14,_DD_03.JPG
