### ISSUE TITLE
Community promotion ad on Drupal Answers

### ISSUE THREAD

**Issue by hugovk** [DCNordics/DCNordics.github.io#15]
Drupal Answers, the Stack Exchange for Drupal, is looking for free ads to help promote the Drupal community on their site.

I've made one for DrupalCamp Nordics: 

http://meta.drupal.stackexchange.com/a/3625/27135

---

[![First DrupalCamp Nordics in Helsinki 11-12 May 2017][1]][2]

  [1]: https://i.stack.imgur.com/xODYW.png
  [2]: http://www.drupalcampnordics.com/

---

Please help it to six upvotes and DrupalCamp Nordics be advertised on Stack Exchange!

**Comment by mikaelkundert** [comment]
Thanks, I've promoted this in Twitter and Slack.
