### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Krisseck** [DCNordics/DCNordics.github.io#5]
I'd say we need a landing page as soon as possible. 

It should include a subscription form (what's the situation with #2 ?) for newsletter, so we can gather interest about the event.

Branding #1 is probably still under development, but I think we can just use some basic styling (maybe default Bootstrap?), to get a basic page going. We can probably write about the idea of the DC Nordics, the location and dates in 2017, what we are looking for currently etc.

**Comment by mikaelkundert** [comment]
Hi! We're working the landing page too in a branch for issue #1 . It will include subscription etc. - The deadline for the branding is 21th day, so I think we can wait until then?

I'm currently in a process of getting G Suite, so that we can setup subscription form with Mailchimp.

**Comment by oetseli** [comment]
Mikael's idea was to vote on #1 if we get more than one suggestion. My suggestion has all the necessary parts for now, including an implementation of index.html. Obviously it's an unfinished initial version as far as features and frontend details go. I'm also not sure how the subscription is going to work with our selected mail service, but there's currently a button link for it. It's most likely a dumb non-solution and can be changed to a form :).

**Comment by mikaelkundert** [comment]
Merged, thanks!
